PREFIX sch: <http://purl.org/net/schemarama#>
PREFIX void: <http://rdfs.org/ns/void#>
PREFIX dgu: <http://reference.data.gov.uk/def/reference/>
PREFIX status: <http://reference.data.gov.uk/def/status/>

CONSTRUCT {
  [] a sch:Error;
    sch:message "Missing void:uriRegexPattern property";
    sch:implicated ?x.
} WHERE {
  ?x a dgu:URISet.
  OPTIONAL {
    ?x void:uriRegexPattern ?r
  }
  FILTER ( !bound(?r) )
}
