PREFIX sch: <http://purl.org/net/schemarama#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

CONSTRUCT {
  [] a sch:Error;
    sch:message "Terms should have an rdfs:label and an rdfs:comment";
    sch:implicated ?x.
    
} WHERE {
  {
	  {
	    ?x a owl:Ontology.
	  }  
	  {
	    ?x a rdfs:Class.
	  }
	  UNION
	  {
	    ?x a owl:Class.  
	  }
	  UNION
	  {
	    ?x a rdf:Property.
	  }
	  UNION
	  {
	    ?x a owl:DatatypeProperty.
	  }
	  UNION
	  {
	    ?x a owl:ObjectProperty.
	  }	  
  }
  OPTIONAL {
    ?x rdfs:label ?label.
  }
  OPTIONAL {
    ?x rdfs:comment ?comment.
  }  
  FILTER ( !bound(?label) || !bound(?comment) )
}